r"""create sms module tables (sms_phone_numbers, sms_inbound, sms_deliveries, sms_telegram_links)

Revision ID: 0017_create_sms_module
Revises: 0016_backfill_team_leaders
Create Date: 2026-07-09

Модуль «СМС» — полное слияние SMS-агрегатора в CRM (ADR-030,
03-data-model.md#таблицы-sms-модуля). Четыре новые таблицы. **Асимметрия ключей
(ADR-030 §2):** собственные PK доменных таблиц — `BIGINT GENERATED BY DEFAULT AS
IDENTITY` (донорская идиома; keyset-курсор по `(received_at, id)`); внешние ссылки
на команды/пользователей — `UUID` (FK на CRM `teams(id)`/`users(id)`).

`upgrade()` создаёт (в порядке FK-зависимостей): sms_phone_numbers, sms_inbound
(+3 индекса), sms_deliveries (+CHECK/UNIQUE/retry-индекс), sms_telegram_links
(+индекс). Таблицы стартуют пустыми (исторические SMS-данные не мигрируются — TD).
`downgrade()` — DROP в обратном порядке (из-за FK sms_deliveries → sms_inbound).
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0017_create_sms_module"
down_revision: str | None = "0016_backfill_team_leaders"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "sms_phone_numbers",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("phone_number", sa.Text(), nullable=False),
        sa.Column("team_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("added_by_user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column("login", sa.Text(), nullable=True),
        sa.Column("app_name", sa.Text(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.PrimaryKeyConstraint("id", name="pk_sms_phone_numbers"),
        sa.UniqueConstraint("phone_number", name="uq_sms_phone_numbers_phone_number"),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
            name="fk_sms_phone_numbers_team_id",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["added_by_user_id"],
            ["users.id"],
            name="fk_sms_phone_numbers_added_by_user_id",
            ondelete="SET NULL",
        ),
    )
    op.create_index("ix_sms_phone_numbers_team_id", "sms_phone_numbers", ["team_id"])

    op.create_table(
        "sms_inbound",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("twilio_message_sid", sa.Text(), nullable=True),
        sa.Column("from_number", sa.Text(), nullable=False),
        sa.Column("to_number", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("team_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("raw_payload", postgresql.JSONB(), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.PrimaryKeyConstraint("id", name="pk_sms_inbound"),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
            name="fk_sms_inbound_team_id",
            ondelete="SET NULL",
        ),
    )
    # Дедуп ретраев webhook по MessageSid (NULL-SID не конфликтуют).
    op.create_index(
        "sms_inbound_sid_uq",
        "sms_inbound",
        ["twilio_message_sid"],
        unique=True,
        postgresql_where=sa.text("twilio_message_sid IS NOT NULL"),
    )
    # Листинг ленты по номеру/набору + keyset (ORDER BY received_at DESC, id DESC).
    op.create_index(
        "ix_sms_inbound_to_number_received",
        "sms_inbound",
        ["to_number", sa.text("received_at DESC"), sa.text("id DESC")],
    )
    op.create_index(
        "ix_sms_inbound_team_id_partial",
        "sms_inbound",
        ["team_id"],
        postgresql_where=sa.text("team_id IS NOT NULL"),
    )

    op.create_table(
        "sms_deliveries",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("inbound_sms_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False, server_default=sa.text("'pending'")),
        sa.Column("attempts", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.PrimaryKeyConstraint("id", name="pk_sms_deliveries"),
        sa.ForeignKeyConstraint(
            ["inbound_sms_id"],
            ["sms_inbound.id"],
            name="fk_sms_deliveries_inbound_sms_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_sms_deliveries_user_id",
            ondelete="CASCADE",
        ),
        sa.CheckConstraint(
            "status IN ('pending','sent','failed','dead')",
            name="ck_sms_deliveries_status",
        ),
        sa.UniqueConstraint(
            "inbound_sms_id",
            "telegram_user_id",
            name="uq_sms_deliveries_sms_chat",
        ),
    )
    # Выборка кандидатов на retry (retry-монитор).
    op.create_index(
        "ix_sms_deliveries_retry",
        "sms_deliveries",
        ["status", "attempts"],
        postgresql_where=sa.text("status IN ('pending','failed')"),
    )

    op.create_table(
        "sms_telegram_links",
        # telegram_user_id = внешний chat_id (upsert), НЕ autoincrement/serial.
        sa.Column(
            "telegram_user_id",
            sa.BigInteger(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("dead_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("telegram_user_id", name="pk_sms_telegram_links"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_sms_telegram_links_user_id",
            ondelete="CASCADE",
        ),
    )
    op.create_index("ix_sms_telegram_links_user_id", "sms_telegram_links", ["user_id"])


def downgrade() -> None:
    op.drop_index("ix_sms_telegram_links_user_id", table_name="sms_telegram_links")
    op.drop_table("sms_telegram_links")

    op.drop_index("ix_sms_deliveries_retry", table_name="sms_deliveries")
    op.drop_table("sms_deliveries")

    op.drop_index("ix_sms_inbound_team_id_partial", table_name="sms_inbound")
    op.drop_index("ix_sms_inbound_to_number_received", table_name="sms_inbound")
    op.drop_index("sms_inbound_sid_uq", table_name="sms_inbound")
    op.drop_table("sms_inbound")

    op.drop_index("ix_sms_phone_numbers_team_id", table_name="sms_phone_numbers")
    op.drop_table("sms_phone_numbers")
